### ISSUE TITLE
[Bug] Notes with an identical name get overwritten

### ISSUE THREAD

**Issue by ltctceplrm** [erikelisath/keep-to-markdown#10]
After the conversion I noticed I was missing around 115 notes and it seems like notes with an identical name get overwritten, google keep takeout names the files as XXXX, XXXX (1) and XXXX (2), so I think this would be solved if your script uses the file name rather than the title from the json, would it be possible to change this?

Edit: The file with the largest number is the final "surviving" one

**Comment by erikelisath** [comment]
Thank you for reporting the bug.
Let me have a look, what I can do.

**Comment by erikelisath** [comment]
I took a look in my Takeout folder and there wasn't files that you mentioned. 
But instead I know the issue here. When multiple files has the same title only one file with the title will keep.
So I changed the code to keep all the duplicated files because google archived the keepnotes in multiple files with the same title but different content.
Hope this will solve your problem. See #11

**Comment by ltctceplrm** [comment]
Perfect, this indeed fixed the problem, thank you very much.

**Comment by erikelisath** [comment]
Nice to hear that the fix solved your problem well!
