### ISSUE TITLE
Photos / Pictures are not displayed after conversion in Nextcloud Android App and Nextcloud Notes Android App

### ISSUE THREAD

**Issue by ant0nwax** [erikelisath/keep-to-markdown#13]
Hi Erik,

very much thanks for your script to convert HTML to MD and even adding the attached photos worked for me
They are displayed in the Nextcloud Web App in e.g. Brave Browser
allow me just a question, I am not requesting you to fix anything

Did you manage to use an Android App for watching Notes with Attachments?
The Nextcloud Android App and the Nextcloud Notes Android App cannot follow the link ressources/.... for the image tag in MD.

Thank you for your inspiriation and time.

**Comment by erikelisath** [comment]
Hey @ant0nwax ,
I am very sorry for my very very late reply.
Unfortunately I can't help you because I don't use Android app for notes, I only use the official Nextcloud iPhone Note app. 
I hope you have found what you are looking for in the meantime.
The implementation of my script I only tested and used with a desktop app.

good luck!
